[bibliography]
== Bibliography

* [[[PRIVISA,1]]] RISC-V Privileged specification
https://github.com/riscv/riscv-isa-manual/releases/download/Priv-v1.12/riscv-privileged-20211203.pdf

* [[[RATS,2]]] IETF RFC 9334 Remote ATtestation procedureS (RATS) Architecture
https://datatracker.ietf.org/doc/rfc9334/

* [[[DICE,3]]] TCG DICE Attestation Architecture, Version 1.00 Revision 0.23
https://trustedcomputinggroup.org/resource/dice-attestation-architecture/

* [[[SPDM,4]]] DMTF DSP0274 Security Protocol and Data Model (SPDM) Specification, Version 1.2.3
https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.3.pdf

* [[[SBI,5]]] RISC-V Supervisor Binary Interface
https://github.com/riscv-non-isa/riscv-sbi-doc[riscv-non-isa/riscv-sbi-doc]

* [[[RVIDBG,6]]] RISC-V Debug Specification Standard
https://github.com/riscv/riscv-debug-spec/blob/master/riscv-debug-stable.pdf

* [[[OT,7]]] OpenTitan
https://opentitan.org/

* [[[TCGG,8]]] Trusted Computing Group (TCG) Glossary, Version 1.1 Revision 1.0
https://trustedcomputinggroup.org/resource/tcg-glossary/

* [[[RVIAIA,9]]] The RISC-V Advanced Interrupt Architecture Document v0.2.1-draft
https://github.com/riscv/riscv-aia/releases[https://github.com/riscv/riscv-aia/releases

* [[[RVINACL,10]]] The RISC-V Nested Acceleration ("NACL") extension
https://github.com/riscv-non-isa/riscv-sbi-doc/releases/download/v2.0-rc8/riscv-sbi.pdf

* [[[EAT,11]]] IETF Entity Attestation Token (EAT)
https://datatracker.ietf.org/doc/rfc9711/[https://datatracker.ietf.org/doc/rfc9711/]

* [[[CBOR,12]]] Concise Binary Object Representation
https://datatracker.ietf.org/doc/rfc8949/[https://datatracker.ietf.org/doc/rfc8949/

* [[[CWT,13]]] CBOR Web Token
https://datatracker.ietf.org/doc/rfc8392/[https://datatracker.ietf.org/doc/rfc8392/

* [[[UCCS,14]]] Unprotected CWT Claims Sets
https://datatracker.ietf.org/doc/draft-ietf-rats-uccs/[https://datatracker.ietf.org/doc/draft-ietf-rats-uccs/

* [[[COSE,15]]] CBOR Object Signing and Encryption
https://datatracker.ietf.org/doc/rfc9052/[https://datatracker.ietf.org/doc/rfc9052/

* [[[Hash_Algorithm_Names,16]]] IANA Hash Function Textual Names
https://www.iana.org/assignments/hash-function-text-names/hash-function-text-names.xhtml[https://www.iana.org/assignments/hash-function-text-names/hash-function-text-names.xhtml

* [[[TCG_Client,17]]] TCG PC Client Platform Profile
https://trustedcomputinggroup.org/resource/pc-client-specific-platform-firmware-profile-specification/

* [[[X509,18]]] X.509 Certificate Profile
https://www.rfc-editor.org/rfc/rfc5280[https://www.rfc-editor.org/rfc/rfc5280

* [[[X509_DSA,19]]] X.509 Algorithms for DSA and ECDSA
https://datatracker.ietf.org/doc/rfc5758/[https://datatracker.ietf.org/doc/rfc5758/

* [[[RVISD,20]]] RISC-V Supervisor Domain Access Protection
https://github.com/riscv/riscv-smmtt/releases/download/v1.0.4/smmtt-spec.pdf

* [[[RVISEC,21]]] RISC-V Security Model
https://github.com/riscv-non-isa/riscv-security-model/releases/download/v1.0/riscv-platform-security-model.pdf

* [[[RVICOVEIO,22]]] RISC-V CoVE-IO
https://github.com/riscv-non-isa/riscv-ap-tee-io/releases/download/v0.1.0/riscv-cove-io.pdf

* [[[UEFI, 23]]] Unified Extensible Firmware Interface (UEFI) Specification v2.11
https://uefi.org/specs/UEFI/2.11/index.html

* [[[RFC8032,24]]] IETF RFC 8032 Edwards-Curve Digital Signature Algorithm (EdDSA)
https://datatracker.ietf.org/doc/rfc8032/

* [[[DSS,25]]] National Institute of Standards and Technology, "Digital Signature Standard (DSS)", FIPS 186-5, DOI 10.6028/NIST.FIPS.186-5, February 2023
https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf

* [[[RFC5752,26]]] IETF RFC 5752 Multiple Signatures in Cryptographic Message Syntax (CMS)
https://datatracker.ietf.org/doc/rfc5752/

bibliography::[]
