# This work flow includes source and PDF in Release.  It relies on the build-pdf workflow to create the PDF.
#
# NOTE: At this time it only runs manually.

name: Create Document Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version, e.g. X.Y.Z:'
        required: true
        type: string
      prerelease:
        description: 'Tag as a pre-release?'
        required: false
        type: boolean
        default: true
      draft:
        description: 'Create release as a draft?'
        required: false
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/build-pdf.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.build.outputs.pdf-name }}
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ needs.build.outputs.pdf-name }}
        tag_name: v${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        draft: ${{ github.event.inputs.draft }}
        prerelease: ${{ github.event.inputs.prerelease }}
